### ISSUE TITLE
PreEvoMoves blank for USUM

### ISSUE THREAD

**Issue by fdeblasio** [AsparagusEduardo/PoryMoves#5]
The PreEvoMoves fields for every single Pokemon is blank in moveParser/db/gen/usum.json

**Comment by AsparagusEduardo** [comment]
Updated USUM's json.

For now you can download it here until a new release comes out:
https://github.com/AsparagusEduardo/PoryMoves/blob/master/moveParser/db/gen/usum.json

I'll leave the issue open until it does.

**Comment by AsparagusEduardo** [comment]
10,000 years later, I finally fixed the file content in the 1.4.0 zip for both this and the missing tm.txt and tutor.txt files.
